[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake clang"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake clang"
]

[target.armv7-unknown-linux-musleabihf]
pre-build = [
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake clang"
]
